import { ChurchEvent, RosterAssignment, User } from './types';

export const MOCK_USERS: Record<string, User> = {
  volunteer: {
    id: 'vol-mateo',
    name: 'Mateo',
    role: 'volunteer',
    roleTitle: 'Servidor Voluntario',
    campus: 'Sede Central',
    ministry: 'Niños & Familia',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDo7evOMP6Psc9bvp2ndP39Q7FBVosfwLbXnnDBXkqvZjfTWrgwBD6uuS4UymAAldRMlAkNqOxFoT9jIe9bwlTSbCC7Sl-kpKsd7YoV0REVjX4OfZZnr7CYXjbM-joLpStWEKeUj2yBgL32IwKwjdqbjQuVKu3fUSqbC8h2e2jrryKat8uezCPzMognh0y7AzkLmy580RujiA4ciKnPUOqTuEmWgwsJPlhrSzaURSX07GG_pcGbuni7',
    phone: '+54 9 11 4523-8891',
    status: 'Activo',
    turnosCumplidos: 24,
  },
  leader: {
    id: 'lead-laura',
    name: 'Pastora Laura Gómez',
    role: 'leader',
    roleTitle: 'Coordinadora de Área (Alabanza y Niños)',
    campus: 'Sede Central',
    ministry: 'Niños & Familia',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
    phone: '+54 9 11 3982-1144',
    status: 'Activo',
    turnosCumplidos: 96,
  },
  superadmin: {
    id: 'admin-daniel',
    name: 'Pastor Daniel',
    role: 'superadmin',
    roleTitle: 'Pastor General & Director Ejecutivo',
    campus: 'Sede Central',
    ministry: 'Pastoral',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCzbxaTGStx5xCswy_dFkgLUFTWrLX5EdmBsr_obhe7vjV_vpypjSkfLEvymAY_yaEcCw1WsNRioIwCr0vIjd1SEN53_aCSLESK3X8bTGKQApCYTC7cr9p4C_kVmpnk7nsVT4HD8O8moO1CgUQSYw8wGi931ImSZ0jJbX5L6R8mqrwbPjqBduYiVAx4-z5CKM4UuldyWfYwVWioHRfhSF-L1cKAaLgfsn2uEKq7F8f1dtlI0sAcYpmz',
    phone: '+54 9 11 6500-1200',
    status: 'Activo',
    turnosCumplidos: 180,
  },
};

export const INITIAL_EVENTS: ChurchEvent[] = [
  {
    id: 'evt-oct-12-central',
    title: 'Culto Dominical & Kids Joy',
    campus: 'Sede Central',
    locationDetail: 'Sede Central — Salón Infantil Kids Joy · Pabellón Este',
    date: '2024-10-12',
    dateFormatted: 'Domingo 12 Oct',
    time: '10:00 AM',
    arrivalPrayerTime: '9:15 AM',
    category: 'Culto Regular',
    requiredVolunteers: 12,
    description: 'Servicio matutino con aulas infantiles abiertas desde cuna hasta 11 años.',
  },
  {
    id: 'evt-oct-12-norte',
    title: 'Culto Familiar Sede Norte',
    campus: 'Sede Norte',
    locationDetail: 'Sede Norte — Auditorio Principal Norte',
    date: '2024-10-12',
    dateFormatted: 'Domingo 12 Oct',
    time: '11:30 AM',
    arrivalPrayerTime: '10:45 AM',
    category: 'Culto Regular',
    requiredVolunteers: 8,
    description: 'Servicio dominical congregacional Sede Norte.',
  },
  {
    id: 'evt-oct-19-central',
    title: 'Culto de Adoración & Niños',
    campus: 'Sede Central',
    locationDetail: 'Sede Central — Salón Infantil Kids Joy',
    date: '2024-10-19',
    dateFormatted: 'Domingo 19 Oct',
    time: '10:00 AM',
    arrivalPrayerTime: '9:15 AM',
    category: 'Culto Regular',
    requiredVolunteers: 14,
    description: 'Celebración dominical y programa especial de creatividad bíblica.',
  },
  {
    id: 'evt-oct-19-norte',
    title: 'Culto de Adoración y Alabanza',
    campus: 'Sede Norte',
    locationDetail: 'Sede Norte — Auditorio Norte',
    date: '2024-10-19',
    dateFormatted: 'Domingo 19 Oct',
    time: '11:30 AM',
    arrivalPrayerTime: '10:45 AM',
    category: 'Culto Regular',
    requiredVolunteers: 7,
    description: 'Servicio dominical con énfasis en la alabanza comunitaria.',
  },
  {
    id: 'evt-oct-26-central',
    title: 'Capacitación Líderes de Niños',
    campus: 'Sede Central',
    locationDetail: 'Sede Central — Salón Multiusos Kids Joy',
    date: '2024-10-26',
    dateFormatted: 'Sábado 26 Oct',
    time: '04:00 PM',
    arrivalPrayerTime: '3:30 PM',
    category: 'Capacitación',
    requiredVolunteers: 18,
    description: 'Convocatoria general para maestros y auxiliares de todas las sedes.',
  },
  {
    id: 'evt-oct-27-norte',
    title: 'Culto Evangelístico & Bautismos',
    campus: 'Sede Norte',
    locationDetail: 'Sede Norte — Patio y Templo Norte',
    date: '2024-10-27',
    dateFormatted: 'Domingo 27 Oct',
    time: '10:30 AM',
    arrivalPrayerTime: '9:45 AM',
    category: 'Especial',
    requiredVolunteers: 10,
    description: 'Ceremonia de bautismos en agua y celebración evangelística.',
  },
  {
    id: 'evt-nov-03-central',
    title: 'Santa Cena & Alabanza Unida',
    campus: 'Sede Central',
    locationDetail: 'Sede Central — Templo Mayor',
    date: '2024-11-03',
    dateFormatted: 'Domingo 03 Nov',
    time: '10:00 AM',
    arrivalPrayerTime: '9:00 AM',
    category: 'Especial',
    requiredVolunteers: 20,
    description: 'Primer domingo del mes: Santa Cena comunitaria y ministerio unido.',
  },
];

export const INITIAL_ASSIGNMENTS: RosterAssignment[] = [
  // Mateo's key shift (from mockup)
  {
    id: 'asg-mateo-oct-12',
    eventId: 'evt-oct-12-central',
    volunteerId: 'vol-mateo',
    volunteerName: 'Mateo',
    volunteerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDo7evOMP6Psc9bvp2ndP39Q7FBVosfwLbXnnDBXkqvZjfTWrgwBD6uuS4UymAAldRMlAkNqOxFoT9jIe9bwlTSbCC7Sl-kpKsd7YoV0REVjX4OfZZnr7CYXjbM-joLpStWEKeUj2yBgL32IwKwjdqbjQuVKu3fUSqbC8h2e2jrryKat8uezCPzMognh0y7AzkLmy580RujiA4ciKnPUOqTuEmWgwsJPlhrSzaURSX07GG_pcGbuni7',
    ministry: 'Niños & Familia',
    roleName: 'Maestro Principal (Grupo 6–8 años)',
    theme: '«El valor de compartir historias»',
    status: 'Pendiente',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  // Mateo second shift
  {
    id: 'asg-mateo-oct-19',
    eventId: 'evt-oct-19-central',
    volunteerId: 'vol-mateo',
    volunteerName: 'Mateo',
    volunteerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDo7evOMP6Psc9bvp2ndP39Q7FBVosfwLbXnnDBXkqvZjfTWrgwBD6uuS4UymAAldRMlAkNqOxFoT9jIe9bwlTSbCC7Sl-kpKsd7YoV0REVjX4OfZZnr7CYXjbM-joLpStWEKeUj2yBgL32IwKwjdqbjQuVKu3fUSqbC8h2e2jrryKat8uezCPzMognh0y7AzkLmy580RujiA4ciKnPUOqTuEmWgwsJPlhrSzaURSX07GG_pcGbuni7',
    ministry: 'Niños & Familia',
    roleName: 'Maestro Principal (Grupo 6–8 años)',
    theme: '«David y la valentía del corazón»',
    status: 'Confirmado',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  // Mateo training convocation
  {
    id: 'asg-mateo-oct-26',
    eventId: 'evt-oct-26-central',
    volunteerId: 'vol-mateo',
    volunteerName: 'Mateo',
    volunteerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDo7evOMP6Psc9bvp2ndP39Q7FBVosfwLbXnnDBXkqvZjfTWrgwBD6uuS4UymAAldRMlAkNqOxFoT9jIe9bwlTSbCC7Sl-kpKsd7YoV0REVjX4OfZZnr7CYXjbM-joLpStWEKeUj2yBgL32IwKwjdqbjQuVKu3fUSqbC8h2e2jrryKat8uezCPzMognh0y7AzkLmy580RujiA4ciKnPUOqTuEmWgwsJPlhrSzaURSX07GG_pcGbuni7',
    ministry: 'Niños & Familia',
    roleName: 'Capacitación Líderes de Niños',
    status: 'Confirmado',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  // María Pérez (Candidate for replacement)
  {
    id: 'asg-maria-oct-19',
    eventId: 'evt-oct-19-central',
    volunteerId: 'vol-maria',
    volunteerName: 'María Pérez',
    volunteerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    ministry: 'Niños & Familia',
    roleName: 'Auxiliar de Aula (3-5 años)',
    status: 'Confirmado',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  // Carlos Ruiz (Worship - Drums)
  {
    id: 'asg-carlos-oct-12',
    eventId: 'evt-oct-12-central',
    volunteerId: 'vol-carlos',
    volunteerName: 'Carlos Ruiz',
    volunteerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    ministry: 'Alabanza & Adoración',
    roleName: 'Batería',
    status: 'Confirmado',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  {
    id: 'asg-carlos-oct-19',
    eventId: 'evt-oct-19-central',
    volunteerId: 'vol-carlos',
    volunteerName: 'Carlos Ruiz',
    volunteerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    ministry: 'Alabanza & Adoración',
    roleName: 'Batería',
    status: 'Pendiente',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  // Sofía Castro (Worship - Vocals / Acoustic)
  {
    id: 'asg-sofia-oct-12',
    eventId: 'evt-oct-12-central',
    volunteerId: 'vol-sofia',
    volunteerName: 'Sofía Castro',
    volunteerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    ministry: 'Alabanza & Adoración',
    roleName: 'Voz Principal & Guitarra',
    status: 'Confirmado',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  {
    id: 'asg-sofia-oct-19',
    eventId: 'evt-oct-19-central',
    volunteerId: 'vol-sofia',
    volunteerName: 'Sofía Castro',
    volunteerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    ministry: 'Alabanza & Adoración',
    roleName: 'Voz Armonía',
    status: 'Confirmado',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  // Juan Méndez (Hospitality / Protocol)
  {
    id: 'asg-juan-oct-12',
    eventId: 'evt-oct-12-central',
    volunteerId: 'vol-juan',
    volunteerName: 'Juan Méndez',
    volunteerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    ministry: 'Protocolo',
    roleName: 'Recepción y Bienvenida',
    status: 'Confirmado',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  {
    id: 'asg-juan-oct-19',
    eventId: 'evt-oct-19-central',
    volunteerId: 'vol-juan',
    volunteerName: 'Juan Méndez',
    volunteerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    ministry: 'Protocolo',
    roleName: 'Ujier Puerta Principal',
    status: 'Pendiente',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  // Valentina Morales (Multimedia)
  {
    id: 'asg-valentina-oct-12',
    eventId: 'evt-oct-12-central',
    volunteerId: 'vol-valentina',
    volunteerName: 'Valentina Morales',
    volunteerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    ministry: 'Multimedia',
    roleName: 'Proyección & Letras',
    status: 'Confirmado',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  },
  // Sede Norte assignments
  {
    id: 'asg-esteban-oct-12-norte',
    eventId: 'evt-oct-12-norte',
    volunteerId: 'vol-esteban',
    volunteerName: 'Esteban Ríos',
    volunteerAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    ministry: 'Alabanza & Adoración',
    roleName: 'Líder de Alabanza Norte',
    status: 'Confirmado',
    coordinatorName: 'Pastor Daniel',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCzbxaTGStx5xCswy_dFkgLUFTWrLX5EdmBsr_obhe7vjV_vpypjSkfLEvymAY_yaEcCw1WsNRioIwCr0vIjd1SEN53_aCSLESK3X8bTGKQApCYTC7cr9p4C_kVmpnk7nsVT4HD8O8moO1CgUQSYw8wGi931ImSZ0jJbX5L6R8mqrwbPjqBduYiVAx4-z5CKM4UuldyWfYwVWioHRfhSF-L1cKAaLgfsn2uEKq7F8f1dtlI0sAcYpmz',
  },
  {
    id: 'asg-claudia-oct-12-norte',
    eventId: 'evt-oct-12-norte',
    volunteerId: 'vol-claudia',
    volunteerName: 'Claudia Vega',
    volunteerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    ministry: 'Niños & Familia',
    roleName: 'Maestra Kids Norte',
    status: 'Confirmado',
    coordinatorName: 'Pastor Daniel',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCzbxaTGStx5xCswy_dFkgLUFTWrLX5EdmBsr_obhe7vjV_vpypjSkfLEvymAY_yaEcCw1WsNRioIwCr0vIjd1SEN53_aCSLESK3X8bTGKQApCYTC7cr9p4C_kVmpnk7nsVT4HD8O8moO1CgUQSYw8wGi931ImSZ0jJbX5L6R8mqrwbPjqBduYiVAx4-z5CKM4UuldyWfYwVWioHRfhSF-L1cKAaLgfsn2uEKq7F8f1dtlI0sAcYpmz',
  },
  // November 03 Vacancy (Pre-seeded so Leader can test AI suggestion even before Mateo requests replacement!)
  {
    id: 'asg-nov-03-vacant',
    eventId: 'evt-nov-03-central',
    volunteerId: 'vol-vacant-1',
    volunteerName: 'Vacante (Sin Servidor)',
    volunteerAvatar: '',
    ministry: 'Niños & Familia',
    roleName: 'Maestro Auxiliar (Grupo 6–8 años)',
    status: 'Rechazado',
    replacementReason: 'Vacante detectada por sistema de planificación',
    coordinatorName: 'Pastora Laura Gómez',
    coordinatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsxvoyPntrjaqu3Vylm3Ynk7DHPq6KTgKLKLH-gnpoLJ2IgjhPKuruSrpGdseT1oXWB8ttdVSXfqm0o_ClkjTfUJ-PXOvuYVrC2uDi9Vcu1CqlCuy0FuaMkphc-bfOQD3SbW5__Gio-uV2LmcfjibIZZLy2LIhue2mec_F-vl-ysYcSXSzyOs7ENnZd7k3NYCWOJf1_wJaOfVCd7CGXhtoVQIMGvU8I3NKJAI7NSQp5u6lJ5Jx0688',
  }
];

export const VOLUNTEER_DATABASE = [
  {
    id: 'vol-mateo',
    name: 'Mateo',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDo7evOMP6Psc9bvp2ndP39Q7FBVosfwLbXnnDBXkqvZjfTWrgwBD6uuS4UymAAldRMlAkNqOxFoT9jIe9bwlTSbCC7Sl-kpKsd7YoV0REVjX4OfZZnr7CYXjbM-joLpStWEKeUj2yBgL32IwKwjdqbjQuVKu3fUSqbC8h2e2jrryKat8uezCPzMognh0y7AzkLmy580RujiA4ciKnPUOqTuEmWgwsJPlhrSzaURSX07GG_pcGbuni7',
    ministry: 'Niños & Familia',
    campus: 'Sede Central',
    preferredRoles: ['Maestro Principal', 'Animación Bíblica'],
    activeShiftsThisMonth: 3,
  },
  {
    id: 'vol-maria',
    name: 'María Pérez',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    ministry: 'Niños & Familia',
    campus: 'Sede Central',
    preferredRoles: ['Maestra de Aula', 'Auxiliar Kids', 'Canto Infantil'],
    activeShiftsThisMonth: 1,
    aiRecommendationScore: 98,
    matchReason: '100% de afinidad pedagógica, disponible en la franja horaria y sin turno previo ese fin de semana.',
  },
  {
    id: 'vol-carlos',
    name: 'Carlos Ruiz',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    ministry: 'Alabanza & Adoración',
    campus: 'Sede Central',
    preferredRoles: ['Batería', 'Percusión'],
    activeShiftsThisMonth: 2,
  },
  {
    id: 'vol-sofia',
    name: 'Sofía Castro',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    ministry: 'Alabanza & Adoración',
    campus: 'Sede Central',
    preferredRoles: ['Voz', 'Guitarra Acústica'],
    activeShiftsThisMonth: 3,
  },
  {
    id: 'vol-juan',
    name: 'Juan Méndez',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    ministry: 'Protocolo',
    campus: 'Sede Central',
    preferredRoles: ['Bienvenida', 'Ujier', 'Comunión'],
    activeShiftsThisMonth: 2,
  },
  {
    id: 'vol-valentina',
    name: 'Valentina Morales',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    ministry: 'Multimedia',
    campus: 'Sede Central',
    preferredRoles: ['Proyección', 'Streaming', 'Cámara'],
    activeShiftsThisMonth: 2,
  },
  {
    id: 'vol-esteban',
    name: 'Esteban Ríos',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    ministry: 'Alabanza & Adoración',
    campus: 'Sede Norte',
    preferredRoles: ['Líder de Alabanza', 'Piano'],
    activeShiftsThisMonth: 2,
  },
  {
    id: 'vol-claudia',
    name: 'Claudia Vega',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    ministry: 'Niños & Familia',
    campus: 'Sede Norte',
    preferredRoles: ['Maestra Kids', 'Cuna'],
    activeShiftsThisMonth: 1,
  },
];
